name       : python-iniconfig
version    : 1.1.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/i/iniconfig/iniconfig-1.1.1.tar.gz : bc3af051d7d14b2ee5ef9969666def0cd1a000e121eaea580d4a313df4b37f32
license    : MIT
component  : programming.python
summary    : brain-dead simple config-ini parsing
description: |
    iniconfig is a small and simple INI-file parser module having a unique set of features
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
